apiVersion: v2
name: helm-gen-self-signed-cert
type: application
version: "0.1.0"
appVersion: "0.1.0"
description: A Helm chart that generates a self signed cert and saves it in a k8s Secret.
home: https://github.com/cognifloyd/helm-gen-self-signed-cert
icon: https://github.com/kubernetes/community/raw/master/icons/png/resources/labeled/secret-128.png
source:
  - https://github.com/cognifloyd/helm-gen-self-signed-cert
keywords:
  - secret
  - x509
  - cert
maintainers:
  - name: Jacob Floyd
    email: cognifloyd@gmail.com
    url: https://github.com/cognifloyd
details:
  Do not use this chart for publicly accessible services!
  This is a companion chart to be used alongside other helm-charts. It uses helm/sprig functions to
  generate a self-signed TLS/x.509 cert. It generates an ephemeral CA, and then generates a signed
  cert using that CA. By default, the cert is good for 365 days, but you can configure that.
  Only use this chart if the security trade-offs for self-signed certs are acceptable
  in your (firewalled) k8s cluster. If not, consider using Let's Encrypt, cert-manager,
  or some other service.
